Adding Requirements
kuldeepsidhu88/book-club pull request #2
Opened 2017-06-03 05:18 UTC by kuldeepsidhu88

2017-06-03 05:19 UTC, kuldeepsidhu88 commented
@santoshbk Review these and update/refine these if you think of anything else.

2017-06-11 17:12 UTC, santoshbk commented on Requirements.md
> +Projects idea is to create an repo for books, which registered users can like, rate and review.
The idea of project is to create a repo for books, which registered users can like, rate and review.

2017-06-11 17:13 UTC, santoshbk commented on Requirements.md
> +Projects idea is to create an repo for books, which registered users can like, rate and review.
Just a grammar mistake, to make sure i was reading everything properly!

2017-06-11 17:14 UTC, santoshbk requested changes
Please correct the changes suggested, so that i can approve and merge! 
thanks

2017-06-12 11:57 UTC, kuldeepsidhu88 commented
@santoshbk Merging this PR as this looks in good state now.

2017-06-12 11:57 UTC, merged